#!/bin/bash
src_path="../../../vendor/mediatek/proprietary/bootable/bootloader/lk/dev/logo/$1"
if [ "$1" = "" ]; then
	echo "Please input resolution,"
	echo "Such as: fhd, hd720, qhd, fwvga"
	exit
fi
echo "starting conversion ..."
p=$1
./tool/bmp_to_raw ./temp0.raw $src_path/"${p}_uboot".bmp
./tool/bmp_to_raw ./temp1.raw $src_path/"${p}_battery".bmp
./tool/bmp_to_raw ./temp2.raw $src_path/"${p}_low_battery".bmp
./tool/bmp_to_raw ./temp3.raw $src_path/"${p}_charger_ov".bmp
./tool/bmp_to_raw ./temp4.raw $src_path/"${p}_num_0".bmp
./tool/bmp_to_raw ./temp5.raw $src_path/"${p}_num_1".bmp
./tool/bmp_to_raw ./temp6.raw $src_path/"${p}_num_2".bmp
./tool/bmp_to_raw ./temp7.raw $src_path/"${p}_num_3".bmp
./tool/bmp_to_raw ./temp8.raw $src_path/"${p}_num_4".bmp
./tool/bmp_to_raw ./temp9.raw $src_path/"${p}_num_5".bmp
./tool/bmp_to_raw ./temp10.raw $src_path/"${p}_num_6".bmp
./tool/bmp_to_raw ./temp11.raw $src_path/"${p}_num_7".bmp
./tool/bmp_to_raw ./temp12.raw $src_path/"${p}_num_8".bmp
./tool/bmp_to_raw ./temp13.raw $src_path/"${p}_num_9".bmp
./tool/bmp_to_raw ./temp14.raw $src_path/"${p}_num_percent".bmp
./tool/bmp_to_raw ./temp15.raw $src_path/"${p}_bat_animation_01".bmp
./tool/bmp_to_raw ./temp16.raw $src_path/"${p}_bat_animation_02".bmp
./tool/bmp_to_raw ./temp17.raw $src_path/"${p}_bat_animation_03".bmp
./tool/bmp_to_raw ./temp18.raw $src_path/"${p}_bat_animation_04".bmp
./tool/bmp_to_raw ./temp19.raw $src_path/"${p}_bat_animation_05".bmp
./tool/bmp_to_raw ./temp20.raw $src_path/"${p}_bat_animation_06".bmp
./tool/bmp_to_raw ./temp21.raw $src_path/"${p}_bat_animation_07".bmp
./tool/bmp_to_raw ./temp22.raw $src_path/"${p}_bat_animation_08".bmp
./tool/bmp_to_raw ./temp23.raw $src_path/"${p}_bat_animation_09".bmp
./tool/bmp_to_raw ./temp24.raw $src_path/"${p}_bat_animation_10".bmp
./tool/bmp_to_raw ./temp25.raw $src_path/"${p}_bat_10_01".bmp
./tool/bmp_to_raw ./temp26.raw $src_path/"${p}_bat_10_02".bmp
./tool/bmp_to_raw ./temp27.raw $src_path/"${p}_bat_10_03".bmp
./tool/bmp_to_raw ./temp28.raw $src_path/"${p}_bat_10_04".bmp
./tool/bmp_to_raw ./temp29.raw $src_path/"${p}_bat_10_05".bmp
./tool/bmp_to_raw ./temp30.raw $src_path/"${p}_bat_10_06".bmp
./tool/bmp_to_raw ./temp31.raw $src_path/"${p}_bat_10_07".bmp
./tool/bmp_to_raw ./temp32.raw $src_path/"${p}_bat_10_08".bmp
./tool/bmp_to_raw ./temp33.raw $src_path/"${p}_bat_10_09".bmp
./tool/bmp_to_raw ./temp34.raw $src_path/"${p}_bat_10_10".bmp
./tool/bmp_to_raw ./temp35.raw $src_path/"${p}_bat_bg".bmp
./tool/bmp_to_raw ./temp36.raw $src_path/"${p}_bat_img".bmp
./tool/bmp_to_raw ./temp37.raw $src_path/"${p}_bat_100".bmp
./tool/bmp_to_raw ./temp38.raw $src_path/"${p}_kernel".bmp
#./tool/bmp_to_raw ./boot_logo $src_path/"${p}_kernel".bmp
./tool/zpipe -l 9 ./"${p}.raw" temp0.raw temp1.raw temp2.raw temp3.raw temp4.raw temp5.raw temp6.raw temp7.raw temp8.raw temp9.raw temp10.raw temp11.raw temp12.raw temp13.raw temp14.raw temp15.raw temp16.raw temp17.raw temp18.raw temp19.raw temp20.raw temp21.raw temp22.raw temp23.raw temp24.raw temp25.raw temp26.raw temp27.raw temp28.raw temp29.raw temp30.raw temp31.raw temp32.raw temp33.raw temp34.raw temp35.raw temp36.raw temp37.raw temp38.raw 
rm -rf ./temp0.raw ./temp1.raw ./temp2.raw ./temp3.raw ./temp4.raw ./temp5.raw ./temp6.raw ./temp7.raw ./temp8.raw ./temp9.raw ./temp10.raw ./temp11.raw ./temp12.raw ./temp13.raw ./temp14.raw ./temp15.raw ./temp16.raw ./temp17.raw ./temp18.raw ./temp19.raw ./temp20.raw ./temp21.raw ./temp22.raw ./temp23.raw ./temp24.raw ./temp25.raw ./temp26.raw ./temp27.raw ./temp28.raw ./temp29.raw ./temp30.raw ./temp31.raw ./temp32.raw ./temp33.raw ./temp34.raw ./temp35.raw ./temp36.raw ./temp37.raw ./temp38.raw ./bootlogo.raw 
./tool/mkimage ./"${p}.raw" ./tool/img_hdr_logo.cfg > ${p}_logo.bin
rm -rf ./"${p}.raw"
echo `file ${p}_logo.bin` ok
echo "conversion finished"