#!/usr/bin/python3

import sys, os, re
from sys import argv
from os.path import (dirname,abspath, sep, realpath)
sys.path.append(sep.join([dirname(realpath(abspath(__file__))), 'xhl', 'script']))
from tool import Tool

if __name__ == '__main__':
    del argv[0]
    if '-e' in argv:
        Tool.SUPPORT_CUSTOMER = True
        del argv[argv.index('-e')]
    Tool.checkDriveList(False)
    Tool.buildimage(argv)