#!/usr/bin/python3

import sys, os, re
from sys import argv
from os.path import (dirname,abspath, sep, realpath)
sys.path.append(sep.join([dirname(realpath(abspath(__file__))), 'xhl', 'script']))
from tool import Tool

if __name__ == '__main__':
    del argv[0]
    Tool.checkDriveList(False)
    if Tool.BEFORE_LOLLIPOP:
        Tool.mm(['r', 'lk', 'k'])
        Tool.mm(['bootimage',])
    else:
        Tool.mm(['clean-lk',])
        Tool.mm(['clean-kernel',])
        Tool.mm(['clean-preloader',])
        Tool.mm()
