#!/usr/bin/python3

import sys, os, re
from sys import argv
from os.path import (dirname,abspath, sep, realpath)
sys.path.append(sep.join([dirname(realpath(abspath(__file__))), 'xhl', 'script']))
from tool import Tool

if __name__ == '__main__':
    keepOut = 'o' in argv or 'O' in argv
    Tool.checkDriveList(True)
    if not Tool.setAutoNew(argv) and not Tool.readParameters():
        Tool.setParameters()
    Tool.checkSelect()
    Tool.copyDriverFiles()
    Tool.mm(['new',], keepOut = keepOut)
    Tool.buildimage()
